name: formatting
on: [push]
jobs:
  formatcode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -t tsolucio/corebos-formatter -f ./docker/Dockerfile .
