name: formatting
on: [push]
jobs:
  formatcode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -t tsolucio/corebos-formatter -f ./docker/Dockerfile .
        run: docker run tsolucio/corebos-formatter phpcs.phar --standard=build/cbSR/ci.xml --extensions=inc,js,php,service `cat build/cbSR/cifiles build/cbSR/cifiles.custom`
        run: docker run tsolucio/corebos-formatter eslint -c build/cbSR/eslintci.js `cat build/cbSR/cifilesjs build/cbSR/cifilesjs.custom`
        run: docker run tsolucio/corebos-formatter find . -not -path "./.git/*" -type f -perm /u=x,g=x,o=x -print | sort -f | diff build/cbSR/executables -
        run: docker run tsolucio/corebos-formatter build/cbSR/chksyntax
